#sdk: "/home/ubuntu/.rvm/gems/ruby-1.9.3-p194/gems/rhodes-3.3.4"
sdkversion: 3.3.4
name: test
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.test
  BundleURLScheme: test
wp:
  productid: '17a30700-cc8f-012f-6837-080027c736d0'
symbian:
  uid: '0xe0160e85'
android:
  version: 2.2

extensions: ["json", "another-extension"]
